### ISSUE TITLE
[Bug - models]

### ISSUE THREAD

**Issue by Panedwards** [Traben-0/Entity_Model_Features#10]
Bug: Some Models Don't show when the/y/ are name-specific ones, although the entity is supposed to
![image_2023-04-05_003210865](https://user-images.githubusercontent.com/97967681/229944719-d3165fdb-8f01-4de8-ae72-ebc8ad3b459b.png)

**Comment by Traben-0** [comment]
random entity models had some significant fixes recently please try with version 0.2.12 or newer and reopen if still affected
