### ISSUE TITLE
[Bug - models]

### ISSUE THREAD

**Issue by RinixGG** [Traben-0/Entity_Model_Features#101]
**Describe the bug**
Hello. I loaded a resourcepack that modifies boat models into cars, but the models are spinning like in the video below.

**List and link to broken resourcepacks**
https://vk.com/doc320039022_560457360?hash=IPMbAg3E1x5L2q6Z9OmUNYv6znWbfHXsZHRMW0Hc2vc&dl=2hTWsabVZf6YgzdD2KvWGVSy7azdZ60HnuWS4otW0Z0

**Expected behavior**
![изображение](https://github.com/Traben-0/Entity_Model_Features/assets/73175330/f3e80fd8-8784-4c81-bfe1-dd9a37f9c830)

**Screenshots**

https://github.com/Traben-0/Entity_Model_Features/assets/73175330/12b08909-5d88-4ba7-884b-1e792ec483ac

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - EMF version Release Candidate 1
 - ETF version 4.5.1

**Comment by Traben-0** [comment]
Interesting I'll look into it, it should be a minor animation variable being off

**Comment by Traben-0** [comment]
fixed for rc 2

**Comment by RinixGG** [comment]
![изображение](https://github.com/Traben-0/Entity_Model_Features/assets/73175330/b4393e81-f7ba-4708-9662-44fabbec9b85)
yeah it works now, thx)
