### ISSUE TITLE
[Bug - models]custom helmet model no longer works

### ISSUE THREAD

**Issue by EnderMelody** [Traben-0/Entity_Model_Features#105]
**Describe the bug**
the helmet model for armory conglomery no longer renders properly since the 'release candidate" versions, works fine on previous versions.
**List and link to broken resourcepacks**
https://www.curseforge.com/minecraft/texture-packs/armory-conglomery

**Expected behavior**
correct model working in EMF version 0.2.13
![correct model working in version 0.2.13](https://github.com/Traben-0/Entity_Model_Features/assets/12649140/4b1ca85b-5b02-4a1b-918f-2168c3a81611)

**Screenshots**
broken model in rc1 and rc2:
![broken model in rc1 and rc2](https://github.com/Traben-0/Entity_Model_Features/assets/12649140/9df89c47-ff7e-4e59-bba9-f0bbd6eeb65c)

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - EMF version: rc1 (or rc2)

**Additional context**

**Comment by Traben-0** [comment]
So old EMF was actually doing it wrong, but dont worry it is a simple fix.

This is just the vanilla biped model's headwear layer showing up becuase it hasnt been overridden by a custom part
just add this part to each armor model

{
	"part": "headwear",
}

![2023-09-11_11 16 24](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/58308274-44ec-4582-bf82-80d62760f460)

**Comment by Traben-0** [comment]
Armor expects all of these parts
![image](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/4d487d73-874b-44ef-9d85-3eafa972cbcc)

i'll have documentation up eventually when release is ready

**Comment by Traben-0** [comment]
armor stands also had another minor issue in rc1 & 2 so hold off until rc3

**Comment by EnderMelody** [comment]
so if the resource pack works with optifine then wouldnt this be a comparability issue? im just wondering since the mod is supposed to be compatible with optifine resource packs so wouldnt this "fix" break that?

**Comment by Traben-0** [comment]
armor models do not work with optifine in my understanding

**Comment by EnderMelody** [comment]
oh if that is the case then disregard my question. i didnt look before but the resource pack is actually made for EMF and specifically states that the armor is an addition from optifine, so it is as you said and the pack dev simply needs to update it.
as for updating the pack, im not sure exactly where to put the code provided as when i tried it broke the model even more. can you provide a bit more detail on that part?

**Comment by EnderMelody** [comment]
nevermind i managed to get it to work, was just copying the code snippet which included a comma and broke the model. it works perfectly now thank you.
