### ISSUE TITLE
[1.20.1] Crash when Rendering Easy Villager inside moded containers and EMF and ETF is installed

### ISSUE THREAD

**Issue by ffuentesm** [Traben-0/Entity_Model_Features#116]
The crash happened with the combination of Easy Villagers 1.20.1-1.0.12, Entity Model Features 0.RC.4, Entity Texture Features 4.5.1.

When I open the UI of a copper Barrel, if I have a Villager in my inventory, the game crashes.
That does not happen in vanilla Chests.
If EMF and ETF are not installed the crash does not happen in a moded container (Iron chest, JEI).
If EMF and ETF are installed and I open a moded container (Iron chest, JEI), and there is no Villager item in it, the crash does not happen.
If EMF and ETF are installed and I open a vanilla chest with a Villager item in it, the crash does not happen.

I already reported this error to Easy Villagers, and they said the error was not from their mod.

**Crashlog**
https://crashy.net/b164b113-bbec-40e2-8575-217c1072018e

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - Entity Model Features 0.RC.4
 - Does the issue persist with only EMF installed? no
https://crashy.net/b164b113-bbec-40e2-8575-217c1072018e

![image](https://github.com/Traben-0/Entity_Model_Features/assets/44974827/22675ee8-5c22-45c4-b809-18ac7433c529)

**Comment by Traben-0** [comment]
This would indeed be emf or etf, I'll look into it
