### ISSUE TITLE
[Bug] Crash with 1.0 for Fabric 1.19.2

### ISSUE THREAD

**Issue by grugsy** [Traben-0/Entity_Model_Features#118]
**Describe the bug**
I have no idea. After the crash, the world instantly crashes upon loading.

**Crashlog**

**(please complete the following information):**
 - Minecraft Version: 1.19.2
 - EMF version 1.0
[crash-2023-09-15_22.49.18-client.txt](https://github.com/Traben-0/Entity_Model_Features/files/12639940/crash-2023-09-15_22.49.18-client.txt)
[crash-2023-09-15_22.33.50-client.txt](https://github.com/Traben-0/Entity_Model_Features/files/12639941/crash-2023-09-15_22.33.50-client.txt)

**Comment by Traben-0** [comment]
you are in luck 1.0.1 is coming shortly for 1.19.3 and 1.19.2 to fix this
