### ISSUE TITLE
[Forge 1.19.3] 1.0.1 file is tagged to be for version 1.19.2 even though its supposed to be 1.19.3

### ISSUE THREAD

**Issue by DTech10** [Traben-0/Entity_Model_Features#123]
[[Forge 1.19.3] 1.0.1](https://www.curseforge.com/minecraft/mc-mods/entity-model-features/files/4754283)

**Comment by Traben-0** [comment]
Fixed

**Comment by DTech10** [comment]
> Fixed

uuh for some reason its still tagged for 1.19.2 in curseforge launcher
