### ISSUE TITLE
[Bug - models] Fresh Animations will break randomly and specific mobs will not have eyes

### ISSUE THREAD

**Issue by iMoobert** [Traben-0/Entity_Model_Features#125]
**Describe the bug**

 • There is a high and random chance that when I start Minecraft, for the entire duration of having the program open, specific entities will not have eyes; usually either wolves, cows, or sheep.

**List and link to broken resourcepacks**

• https://www.curseforge.com/minecraft/texture-packs/fresh-animations

**Expected behavior**

• All entities should have eyes

**Screenshots**

https://imgur.com/a/LRIj4Ip

**Versions**

 - Minecraft Version: 1.20.1
 - EMF version: 1.0
 - ETF version if applicable: 4.5.1

**Additional context**

For the duration of specific Minecraft instances, all entities of that type will not have eyes. Closing Minecraft entirely and re-opening it _sometimes_ fixes the issue. It seems random on whether or not any one entity will have eyes or not. Most of the time it is sheep, however, sometimes cows will not have eyes, or wolves. Sometimes both sheep and cows do not have eyes. I will not know until I start up a world and check each entity.

**Comment by Traben-0** [comment]
Do they work with no other mods installed?

**Comment by iMoobert** [comment]
Sorry that took about 10 minutes

Yeah I tried recreating the issue about 4 times but without any other mods installed it works fine

I guess there's an incompatibility in there somewhere; I have 143 other mods in the folder so it'll take a while to figure it out

**Comment by iMoobert** [comment]
This is very strange; I removed all of my mods, tested, and it was working properly.

I added 1/4 of my total mods back + their libraries: nothing broken
I added another 1/4 of my mods: nothing broken
another 1/4: still nothing broken
the last 1/4: still nothing broken

All of my mods are back where they should be, and Fresh Animations still won't break anymore, no matter how many times I restart Minecraft.

Literally nothing has changed lol, I don't understand

**Comment by netcore10** [comment]
I've seen this happen, it sometimes fixes itself when you relaunch, sometimes they lose eyes when you relaunch again, but it's intermittent.

**Comment by CMDRSushijones** [comment]
Hello there! I found out the SOLOUTION TO THE WHITE EYE ERROR!!! 
First: Make sure you use the exact version of the texture pack (example: 1.20.1) 
Second: Install Optifine for the version (You may need to start the version u want to install optifine on once)
Third: Load up a world/ join a server and go to : ESC MENU > settings > video Settings > Quality  and make sure "Custom Entity Models" is turned on!!!! if you dont have "video Settings" etc. Make sure u installed optifine and ran the right installation in your Minecraft Launcher!!!
I hope this will work for you too.
