### ISSUE TITLE
[Bug] Mod file version mismatch on Curse

### ISSUE THREAD

**Issue by Sixdd6** [Traben-0/Entity_Model_Features#128]
**Describe the bug**
The most recent 1.19.2 build on CurseForge is actually a 1.19.3 build as noted by it requiring a newer major forge version.

**To Reproduce**
1. Open CurseForge app
2. Create a 1.19.2 instance on forge
3. Install most recent EMF build
4. Launch game
5. Crash/Profit

**Expected behavior**
The most recent build for 1.19.2 should install properly.

**Crashlog**
[crash-2023-09-22_06.03.16-fml.txt](https://github.com/Traben-0/Entity_Model_Features/files/12700050/crash-2023-09-22_06.03.16-fml.txt)

**(please complete the following information):**
 - Minecraft Version: 1.19.2
 - EMF version: 1.0.1
 - Does the issue persist with only EMF installed? Yes
 - if applicable, provide your modlist or log

**Additional context**
The 1.19.3 file just got mistagged, should be easy fix as the proper version is already there.

**Comment by Traben-0** [comment]
this is already fixed on the website, i literally cannot do anything more
I cant even reupload it as it would reject a reupload

**Comment by Traben-0** [comment]
well i changed the file a little delteed it then reuplaoded the 1.19.3 version, i can only that fixes it on their end

**Comment by Sixdd6** [comment]
Thank you! It's fixed now, or at least the client has updated now.
