### ISSUE TITLE
[Bug] Crash or Compatibility

### ISSUE THREAD

**Issue by knoxhack** [Traben-0/Entity_Model_Features#131]
**Crashlog**
[https://gist.githubusercontent.com/knoxhack/c1ee9cc81acb45ce83305474a4a2e013/raw/60dee1054d1e4609318fc85dedc17e02cbc794bd/Emf](https://gist.githubusercontent.com/knoxhack/c1ee9cc81acb45ce83305474a4a2e013/raw/60dee1054d1e4609318fc85dedc17e02cbc794bd/Emf)

**Comment by Traben-0** [comment]
fixed in recent version
