### ISSUE TITLE
[Bug] Crash or Compatibility

### ISSUE THREAD

**Issue by LordDecay26** [Traben-0/Entity_Model_Features#135]
**Describe the bug**
classpath build incorrect.

**To Reproduce**
install entity model features for forge 1.19.2 and try to launch the game, crash on startup
https://pastebin.com/c27kxVFa
**Expected behavior**
game should load?

**Crashlog**
https://pastebin.com/c27kxVFa

latest.log:
https://pastebin.com/QR6zyHfm

**(please complete the following information):**
- 1.19.2
 - EMF version [e.g. 1.0.2]

**Additional context**

**Comment by EngineerSmith** [comment]
Is there any updates for this issue?

**Comment by Traben-0** [comment]
#115 is pinned on the issue page it has your solution

**Comment by Traben-0** [comment]
you are missing a dependency for emf or another mod
for some reason that triggers this issue and crash message

**Comment by Traben-0** [comment]
i will be trying to look into this and prevent it again

**Comment by LordDecay26** [comment]
unable to locate missing dependency.

**Comment by Traben-0** [comment]
Mod impactfulweather requires forge 43.2.4 or above
Currently, forge is 43.2.3

in your log

**Comment by Traben-0** [comment]
Mod ID: 'forge', Requested by: 'impactfulweather', Expected range: '[43.2.4,)', Actual version: '43.2.3'

**Comment by Traben-0** [comment]
i have also fixed this incorrect crash report issue today so it'll be in the next emf update
