### ISSUE TITLE
[Bug - models] Root bone transformations with multiple models cause inconsistencies

### ISSUE THREAD

**Issue by Thanos1716** [Traben-0/Entity_Model_Features#144]
**Bug description**
Whenever a root bone is transformed by an animation in a secondary model, the transformation also applies to the same root bone in the main model.
If there are no entities rendered in the world that are using the secondary model, then the issue will not occur, (e.g `/kill @e[type=minecraft:chicken]`, reload resources, and then `/summon minecraft:chicken ~ ~ ~` will look fine)
This seems to happen on all entities, but was not present in earlier versions of this mod.

**Example resourcepack**
[bugged-chickens.zip](https://github.com/Traben-0/Entity_Model_Features/files/13371997/bugged-chickens.zip)
More model examples can be provided if necessary.

**Screenshots**
*Optifine:*
![2023-11-16_14 06 07](https://github.com/Traben-0/Entity_Model_Features/assets/80975570/ed0bd430-cd66-4e49-b462-6b0db137b438)

*ETF + EMF (Adult chicken is scaled to 2x its normal size):*
![2023-11-16_14 07 30](https://github.com/Traben-0/Entity_Model_Features/assets/80975570/29fc7719-043c-4a01-b840-1a92c32aa9d3)

**Version information**
 - Minecraft Version: *1.20.2*
 - EMF version: *1.1.0*
 - ETF version: *4.6.1*

**Comment by Traben-0** [comment]
I have been made aware of this is part already

It would help me greatly if you could test 1 thing for me, assuming only 1 of these models is applying this scaling you've mentioned.

If you swap which model is the default and which is the variant (e.g. chicken2.jem) does it still occur?

It might take me several days if not a week to test further myself

**Comment by Traben-0** [comment]
i would agree i'll keep both for now to remind me to use both packs to test

**Comment by Traben-0** [comment]
![2023-11-25_16 21 42](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/40a619ae-ebc3-44a7-a2ec-0c3e03fcc303)
fixed for next update
