### ISSUE TITLE
[Bug] Crash when attempting to render a model that doesn't exist

### ISSUE THREAD

**Issue by Thanos1716** [Traben-0/Entity_Model_Features#148]
**Bug description**
When rendering any entity that has a custom model defined by a properties file, if the file is missing, the game will crash

**To Reproduce**
1. Install [this](https://github.com/Traben-0/Entity_Model_Features/files/13614646/broken-properties.zip) resourcepack example
2. Run the command `/summon minecraft:armor_stand ~ ~ ~ {Small:true}`
3. Observe crash

**Expected behavior**
A warning in the log

**Crashlog**
[crash-2023-12-09_00.49.06-client.txt](https://github.com/Traben-0/Entity_Model_Features/files/13614712/crash-2023-12-09_00.49.06-client.txt)

**Installation**
 - Minecraft Version: 1.20.2
 - EMF version: 1.2
 - Does the issue persist with only EMF installed: Yes (plus ETF and Fabric API)

**Comment by Traben-0** [comment]
i've accidentally fixed this for the next update already
