### ISSUE TITLE
[Version Request] Please update 1.20.1 with the important bugfixes from EMF 1.2

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Traben-0/Entity_Model_Features#155]
**Is your feature request related to a problem? Please describe.**
Yes, 1.20.1 EMF has bugs and performance issues, such as #154 

**Describe the solution you'd like**
Please keep supporting MC 1.20.1 a little longer, I want those bugfixes :( Most other mods haven't updated yet and I don't plan to move away from 1.20.1

**Does OptiFine do this**
No, but who cares about OptiFine

**Additional context**
0.0

**Comment by Traben-0** [comment]
1.20.1 isn't abandoned,  the recent etf rework still needs some fixes and changes and I want them fixed before I push these latest updates back further

**Comment by TBlazeWarriorT** [comment]
@Thanos1716 @Traben-0 Thank you!
