### ISSUE TITLE
[Bug - models] Enderman head block not showing

### ISSUE THREAD

**Issue by DragonFire93** [Traben-0/Entity_Model_Features#164]
**Describe the bug**
The enderman head's (block) is invisible in hotbar, when placed and in the JEI; it stills works (and drops) normally but is invisible.

**List and link to broken resourcepacks**
//

**Expected behavior**
The enderman head shouldn't be invisible

**Screenshots**
![2024-01-18_14 22 04](https://github.com/Traben-0/Entity_Model_Features/assets/85889418/01ffa0ac-ff69-4f19-9721-6b9a672358f9)

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - EMF version: entity_model_features_fabric_1.20.1-1.2.3
 - ETF version:  entity_texture_features_fabric_1.20.1-5.2.1

**Additional context**
Supplementaries: supplementaries-1.20-2.7.23-fabric
Fresh animations: FreshAnimations_v1.8.1

**Comment by Traben-0** [comment]
fresh animations enderman.jem doesn't actually have a head part it is empty so supplementary is reading an empty head this needs to be alterred in FA or more fittingly in supplementaries
