### ISSUE TITLE
[Bug - models] Fresh Animation Extentions not working correctly (Forge)

### ISSUE THREAD

**Issue by ElRokur** [Traben-0/Entity_Model_Features#179]
**Describe the bug**
So several models of Fresh Animation Extentensions dont show:
1. Esqueletons dont have quivers
2. Iron golems lose their "vines" and dont show the bright red eyes
3. Drowned dont show bright pixels
4. Spiders have almost all the body invisible (legs and face invisible)

**List and link to broken resourcepacks**

Fresh Animations Extentions
https://www.curseforge.com/minecraft/texture-packs/fresh-animations-extensions

**Expected behavior**

It should look like it does on fabric (i tried the same mods on fabric and it works fine)

**Screenshots**

![2024-03-10_13 46 04](https://github.com/Traben-0/Entity_Model_Features/assets/140526008/e0b9b447-67ee-43c4-936f-bb44bd219900)
![2024-03-10_13 46 16](https://github.com/Traben-0/Entity_Model_Features/assets/140526008/2e02b219-abf1-48b6-87c6-d209665cf66b)
![2024-03-10_13 46 29](https://github.com/Traben-0/Entity_Model_Features/assets/140526008/63d9128c-1af9-4f73-8085-85cce5af3c27)

**(please complete the following information):**
 - Minecraft Version: [1.20.1]
 - EMF version [1.3]
 - ETF version [5.2.3]

**Additional context**
Using embbedium in forge

**Comment by ElRokur** [comment]
Sorry, found it was a bug with ImmediatelyFast mod, it all works fine without it. Brought attention to it https://github.com/RaphiMC/ImmediatelyFast/issues/180#issue-2177868060

**Comment by NolanHewitt** [comment]
On fabric Bart the Enderman has two sets of arms, but all those other issues you listed don't occur

**Comment by GoldenDisk** [comment]
I have the exact same issues but removing the ImmediatelyFast mod did nothing to fix it. After looking around I found out that the oculus mod was causing the issue. So once that was removed it was fixed.
