### ISSUE TITLE
[Bug] Crash or Compatibility, Crash on Launch 

### ISSUE THREAD

**Issue by tana-to** [Traben-0/Entity_Model_Features#182]
**Describe the bug**
when i launch the game it crashes

**Crashlog**
https://mclo.gs/p4Waq3q

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - EMF version: 1.3
 - Does the issue persist with only EMF installed? : no
 - if applicable, provide your modlist or log
 https://mclo.gs/50ozma5

**Comment by Traben-0** [comment]
see #115 for the fix

the issue with this crash blaming emf wrongly has returned in v1.3 and has already been fixed for the next version coming
