### ISSUE TITLE
2022 Zombie Skins - Textures (and likely models) are bugged

### ISSUE THREAD

**Issue by Swagboi7** [Traben-0/Entity_Model_Features#19]
![7860C22C-918F-40D1-800B-DBB8FCD8DA35](https://user-images.githubusercontent.com/106929218/231211761-be0aae1b-863f-4294-a800-325fea97904c.png)

https://www.planetminecraft.com/texture-pack/2022-zombie-skins/

**Comment by Traben-0** [comment]
does this still occur with 0.2.12?
