### ISSUE TITLE
[Bug - models] Iris 1.7.0 causes parts of a custom model to not render

### ISSUE THREAD

**Issue by pnk2u** [Traben-0/Entity_Model_Features#192]
**Describe the bug**
The resource pack _Better Cats!_ changes the model of cats and adds custom parts not part of the vanilla model. The eyes and whiskers do not get rendered when using the new Iris beta 1.7.0 version.

**List and link to broken resourcepacks**
[Better Cats!](https://modrinth.com/resourcepack/better-cats!)

**Expected behavior**
The eyes and whiskers should be visible.

**Screenshots**
![2024-04-04_18 15 40](https://github.com/Traben-0/Entity_Model_Features/assets/159317511/80b1c463-9f43-49b5-b07b-9a52ff9da08a)

> [1] `Iris 1.6.17` - The cat's eyes and whiskers render normally.

---
![2024-04-04_18 19 04](https://github.com/Traben-0/Entity_Model_Features/assets/159317511/d91ac5fb-01e8-4a4d-bfdd-0179c635b728)

> [2] `Iris 1.7.0` - The cat's eyes and whiskers do not render.

---
![2024-04-04_18 24 41](https://github.com/Traben-0/Entity_Model_Features/assets/159317511/8ccfd96e-27f6-410e-b213-2d7f72afedb0)

> [3] `Iris 1.7.0`, `EMF/ETF 2.0/6.0` config screen, custom gui resourcepack - The cat rendering as intended in front of the eye- and whiskerless cat in the background.

---
![2024-04-04_19 33 41](https://github.com/Traben-0/Entity_Model_Features/assets/159317511/bc2ca12a-3328-478f-8985-e2d0336a3232)

> **_Update:_** [4] `Iris 1.7.0`, `EMF/ETF 2.0/6.0` config screen, custom gui resourcepack - The cat's eyes, whiskers, collar and snout rendering in front of the eye- and whiskerless cat in the background.

---

**(please complete the following information):**
 - Minecraft Version: 1.20.4
 - EMF version: 1.3, 2.0
 - ETF version: 5.2.3, 6.0 

**Additional context**

This bug does not occur when using Iris 1.6.17 and also does not occur in the EMF config screen.
EMF 1.3's config screen only renders the missing parts (whiskers + eyes) and the ears. The collar, too, if tamed.
EMF/ETF 2.0/6.0 config screen sometimes renders the cat fully and correctly (screenshot attached) and sometimes it shows the same behaviour as EMF 1.3's config screen except that it also renders the snout and nose.

> **_Update:_** The latter (Screenshot 4) happens specifically and only when the emissive rendering mode is set to `Brighter`. Setting it to `Default` causes it to render normally (Screenshot 3).

The eyes and whiskers get stored in separate texture files and are not part of the main cat texture file.
The resourcepack uses the Optifine random mob texture feature. Disabling it does not fix the bug.
Both the cats' main texture and separately the cat's eyes use this feature.
The eyes also use the emissive texture feature.

**Comment by Traben-0** [comment]
this the distant horizons beta?

**Comment by pnk2u** [comment]
Yes.

**Comment by Traben-0** [comment]
This is known and requires changes on my end once it's out,  I'm looking in to doing it for the beta but I'm doing some other stuff first

**Comment by pnk2u** [comment]
Newest commits of ETF fix this issue. (: Thank you! <3

**Comment by pnk2u** [comment]
EMF/ETF 2.0/6.0 full release has fully fixed this issue.
