### ISSUE TITLE
I'm the first. Make a transitional transparency for for mobs at the boundary of their rendering. 

### ISSUE THREAD

**Issue by YoungSoulluoS** [Traben-0/Entity_Model_Features#2]
I saw the Fade spawn animation feature in Alpha and decided needed to go further.
Perhaps this is already implemented by some mod, but I do not know about it.
But here's an idea.

- For example: rendering a mob in 96 blocks.
- When he are in 96 blocks. The mob appears, but has a completely transparent texture, as the player gets closer to the mob the texture transparency increases to 100% on 90 blocks.
- And vice versa, as they are removed.

**Comment by Traben-0** [comment]
You can partially do this already, etf has a distance from client property,   you could either use progressive more transparent textures over distance with the translucent rendering override   or make lower detail models over distance for a lod effect

**Comment by Traben-0** [comment]
In fact you can also do this with vanilla shaders
