### ISSUE TITLE
[Bug - models] Assorted Allays - detatched body parts

### ISSUE THREAD

**Issue by Swagboi7** [Traben-0/Entity_Model_Features#20]
![DE49553D-0541-420D-B75B-1D5F0BFF49E7](https://user-images.githubusercontent.com/106929218/231212237-5ef0447f-0d06-4040-8f44-f24ff51852ef.png)

https://www.curseforge.com/minecraft/texture-packs/assorted-allays

**Comment by Traben-0** [comment]
please test with 0.2.12 I suspect this has improved or been fixed
