### ISSUE TITLE
[simpler 3d armor] 

### ISSUE THREAD

**Issue by aurora-1-2-3** [Traben-0/Entity_Model_Features#204]
**Is your feature request related to a problem? Please describe.**
The 3d armor feature is great but it's confusing 
Ex. If you are making a 3d armor RP,  you will be confused with "modname_armor..."

**Describe the solution you'd like**
Instead of making the 3d armor to be
zombie_armor_... Or smth
You should make it easier 
Like make it
diamond_armor... Smth
iron_armor.... smth
And for cit 
wizard_armor...smth
enchanter_armor...smth. 

**Does OptiFine do this**
No optifine refuse to add this

**Comment by Traben-0** [comment]
As great as this is it would be fairly difficult, I can think of a few ideas but it's not a priority for now

**Comment by Traben-0** [comment]
This is also fundamentally different from the vanilla model behaviour

**Comment by aurora-1-2-3** [comment]
Hm
You can take your time as much as you want

**Comment by aurora-1-2-3** [comment]
But if people want to make a big pack with 3d armor and cit of that armor
Yeah that's gonna push the performance really hard

**Comment by aurora-1-2-3** [comment]
Since the 3d armor feature you can
Just add another set named
Player_diamond_armor_layer_1.jem
Or
smth
And for the mobs you can do the same
Zombie_iron_armor_layer_1.jem
Or
Smth
Instead of redoing the whole feature 
Add a player armor model 
And separate armor set with a model
If that makes sense

**Comment by Traben-0** [comment]
`outer_armor.jem` and `inner_armor.jem` were added as fallback armor models last update
