### ISSUE TITLE
[BUG] Minecraft crash

### ISSUE THREAD

**Issue by KIRUYXAN** [Traben-0/Entity_Model_Features#206]
**Describe the bug**
All versions of the mod above 1.3 crash minecraft for me

**To Reproduce**
1. Add this mod and dependencies
2. Start minecraft
3. See error

**Expected behavior**
Minecraft must start

**Crashlog**
[logs](https://mclo.gs/zSM5Ixe)

**(please complete the following information):**
 - Minecraft version: 1.20.1
 - EMF version: 2.0+
 - all mods:
![image](https://github.com/Traben-0/Entity_Model_Features/assets/65653126/a4a21f86-82f0-4187-8d74-798fa7dbea37)
![image](https://github.com/Traben-0/Entity_Model_Features/assets/65653126/e93ca732-9997-44ce-b790-44154748990a)

**Comment by Traben-0** [comment]
duplicate https://github.com/Traben-0/Entity_Texture_Features/issues/264

**Comment by Traben-0** [comment]
etf is the root cause anyhow
