### ISSUE TITLE
[able to change jem file names]

### ISSUE THREAD

**Issue by aurora-1-2-3** [Traben-0/Entity_Model_Features#207]
**Is your feature request related to a problem? Please describe.**
Able to change file names would be game changer. I am referring to like
You can have a custom jem file name for easier management 
For example 
Allay_hat.jem
...

Ex. It would be really great for managing and arranging jem files instead of opening all of them to find one or set up a txt file for that you can just rename it to a custom name

**Describe the solution you'd like**
Now for identify 
You can set up a lang file
Or make the allay folder to have a line of code that allows that
If that makes sense. 

**Does OptiFine do this**
No optifine does not allow it

**Additional context**
For context 
Assets/minecraft/emf/cem/allay/
Allay_hat.jem
Allay_cowboy.jem
........

**Comment by Traben-0** [comment]
This will not be something i'll add, 

cons:
- there is no end user benefit.
- this would require a fundamental rework of how ETF and EMF variate things.
- breaks OptiFine backwards compatibility where it doesnt need to
- numbers are simpler than full custom names, and also immedeately make clear that a model has variation to others looking at your pack files
- numbers inherently make the variants group up in the file system when sorting by name
- .jpm files atleast partially provide this functionality
- requires extra files and features to map model names to their renames
- would need to keep back compatibility with the number system anyway and most people will still only use that for many of the above reasons

pros:
pack devs can have more descriptive model file names that no one else will ever see
