### ISSUE TITLE
[Rotation and scaling to cem attachments] CEM animations

### ISSUE THREAD

**Issue by aurora-1-2-3** [Traben-0/Entity_Model_Features#213]
**Is your feature request related to a problem? Please describe.**
This can be extremely useful. 
A great feature
It isn't related to a problem,

**Describe the solution you'd like**
OptiFine version is like this,<br>
```
"attachments": 
{ 

    "attachment_name": [tx, ty, tz]
  },
```
  
  It can be like,
```
"attachments": 
  `{
    "attachment_name": [tx, ty, tz], 
    "attachment_name": [rx, ry, rz], 
    "attachment_name": [sx, sy, sz] 
  },` 
```

**Does OptiFine do this**
This feature is currently the latest feature from OptiFine. Thus it can change

**Additional context**
Items can be like 
![image](https://github.com/Traben-0/Entity_Model_Features/assets/139906198/97c27130-ad1f-4059-8840-04a1c09a7e3b)

**Comment by Traben-0** [comment]
Just put the attachment inside an empty part,  you can then rotate and scale that part normally and it will affect the attachment point inside it. 

Adding attachment specific rotation and scales would just break optifine compat for no reason, when the above takes seconds to setup.

**Comment by aurora-1-2-3** [comment]
empty part?

**Comment by Traben-0** [comment]
I.e add a part/group inside left_arm that doesn't have any boxes and only an attachment point.

That part can then be rotated and scaled

**Comment by aurora-1-2-3** [comment]
just to be clear
like this?
![image](https://github.com/Traben-0/Entity_Model_Features/assets/139906198/69a5f245-7870-499c-9a3e-a090c5f91718)
![image](https://github.com/Traben-0/Entity_Model_Features/assets/139906198/b1b39ed2-8a32-40cd-ada3-243c1e959696)

**Comment by aurora-1-2-3** [comment]
cant find the scale one for the one above
