### ISSUE TITLE
CEM Attachment support for endermen.

### ISSUE THREAD

**Issue by aurora-1-2-3** [Traben-0/Entity_Model_Features#219]
![image](https://github.com/Traben-0/Entity_Model_Features/assets/139906198/d15545ad-9ef8-4a32-a421-98f99de28877)
yeah idk what else to say,
Also if there is a way around the attachments please let me know with a source.

**Comment by Traben-0** [comment]
its planned

**Comment by aurora-1-2-3** [comment]
oh ok, any release date?

**Comment by Traben-0** [comment]
I've been informed OptiFine may be entirely redoing or extending the attachments implementation, so I'm sort of holding off until I see what they do

**Comment by aurora-1-2-3** [comment]
hmm, thanks
