### ISSUE TITLE
[Bug - models] fresh animation has broken the skeleton model, how to fix?

### ISSUE THREAD

**Issue by Dom23575** [Traben-0/Entity_Model_Features#235]
Fresh animation brok the skeleton because when i turn on the resouces pack the skeleton has a extra chest and head floating next to it.

https://modrinth.com/resourcepack/fresh-animations/version/1.9.2

![image](https://github.com/Traben-0/Entity_Model_Features/assets/174743141/3a3e799e-b338-4d26-9964-a9ca3a95066f)

Minecraft version 1.20.6

EMF version 2.1.3

ETF version 6.1.3

**Comment by AnimalFriend1** [comment]
Are you using the 3D Default resource pack? I was able to fix it by going to assets/minecraft/optifine/cem in the 3D Default files and removing the files skeleton.jem, skeleton_body.jpm, skeleton_head.jpm and skeleton_limbs.jpm

**Comment by Dom23575** [comment]
> Are you using the 3D Default resource pack? I was able to fix it by going to assets/minecraft/optifine/cem in the 3D Default files and removing the files skeleton.jem, skeleton_body.jpm, skeleton_head.jpm and skeleton_limbs.jpm

Ah thank you so much that fixed it.

**Comment by Traben-0** [comment]
I'm seeing this is a broken FA addon pack so not an EMF issue then
