### ISSUE TITLE
[Bug - models] Some textures are being misrendered.

### ISSUE THREAD

**Issue by Hexality** [Traben-0/Entity_Model_Features#237]
**Describe the bug**
The textures are being loaded into vanilla models, and custom models don't load.

**List and link to broken resourcepacks**
[Better Cats](https://modrinth.com/resourcepack/better-cats!)
[Wild Wolves](https://modrinth.com/resourcepack/wild-wolves)
[Raven Phantoms](https://modrinth.com/resourcepack/raven-phantoms)

**Expected behavior**
<details>
<summary>Better Cats</summary>
<img src="https://github.com/Traben-0/Entity_Model_Features/assets/17398632/d387870c-aa94-45f1-ba9e-8a7ccd818d23">
</details>
<details>
<summary>Wild Wolves</summary>
<img src="https://github.com/Traben-0/Entity_Model_Features/assets/17398632/d94a5526-4bdd-4acf-9aba-51b32608ac2c">
</details>
<details>
<summary>Raven Phantoms</summary>
<img src="https://github.com/Traben-0/Entity_Model_Features/assets/17398632/a6b11eb8-da6a-4530-86e4-1f4db7d6a679">
</details>

**Screenshots**
<details>
<summary>Better Cats</summary>
<img src="https://github.com/Traben-0/Entity_Model_Features/assets/17398632/43d8b523-a0b6-4823-bf34-0d36fc9214b4">
</details>
<details>
<summary>Wild Wolves</summary>
<img src="https://github.com/Traben-0/Entity_Model_Features/assets/17398632/c431104f-e8a0-4db7-9d35-e2c487f15e07">
</details>
<details>
<summary>Raven Phantoms</summary>
<img src="https://github.com/Traben-0/Entity_Model_Features/assets/17398632/0f9bd09c-cabd-4b9e-b0a8-e98f654f254a">
</details>

**Versions:**
 - Minecraft Version: 1.21
 - EMF version: 2.1.3
 - ETF version:  6.1.3
 - Tested with: IBM Semeru 21 (OpenJ9), Adoptium Temurin 21 (Hotspot) and Oracle Graal 21 (GraalVM)

**Additional context**
https://mclo.gs/9tGPFSf

**Comment by Hexality** [comment]
now zombies and skeletons appear like this, which previously didn't
![image](https://github.com/Traben-0/Entity_Model_Features/assets/17398632/2e765904-8c4f-4ba2-a77a-dcacbaa1ac31)

**Comment by Traben-0** [comment]
what shaders?

**Comment by Hexality** [comment]
Complementary Unbound latest

Em dom., 7 de jul. de 2024 às 01:38, Traben ***@***.***>
escreveu:

**Comment by Traben-0** [comment]
this one ? 
![image](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/e5f4bcac-89ee-4fb0-840d-b4a51477f7c2)

I am having no such issues with it

**Comment by Traben-0** [comment]
ah i see a big update happened yesterday for complimentary 5.2.2 ill check it out

**Comment by Traben-0** [comment]
everything looks normal with Fresh animations, vanilla jem models, FA addons, and the entity health bars pack.
what pack modifies your skeletons?

![2024-07-07_15 39 23](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/801af6f1-7280-40e1-b64f-8e290698c934)
![2024-07-07_15 40 27](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/987fd8aa-30f5-40e4-ad21-12b536c52663)

![2024-07-07_15 37 40](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/76374524-be8d-4c77-bd60-dafb8c797940)

![2024-07-07_15 38 51](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/263c3672-c834-4891-9378-968674be0139)

**Comment by Hexality** [comment]
ok apparently this is the pack conflicting
![image](https://github.com/Traben-0/Entity_Model_Features/assets/17398632/61b106d6-4df9-4b77-ba4f-a5854189966f)
was supposed to change mods to be more immersive, but since its not working, R.I.P I guess.
