### ISSUE TITLE
[Bug - models] Just a little problem

### ISSUE THREAD

**Issue by 0Miuni0** [Traben-0/Entity_Model_Features#24]
**Describe the bug**
Hello, I just noticed a little problem when I'm using Fresh Animation. The Snowy Fox has white eyes. On a normal fox it's alright. I'm not using any texture pack, just Fresh Animation. It's just a little problem that catched my eye. I hope I can help at least a little with this. Thank you for this mod.
[sorry for the broken english]

**List and link to broken resourcepacks**
Fresh Animations 1.8
https://www.curseforge.com/minecraft/texture-packs/fresh-animations/

**Screenshots**
![2023-04-17_12 14 29](https://user-images.githubusercontent.com/130911307/232458952-42cc5d21-f991-4066-b880-2aab4c5e9f31.png)
![2023-04-17_12 15 42](https://user-images.githubusercontent.com/130911307/232458981-2c86ef7f-55b6-4cc3-ba21-734ef4b701c0.png)

**(please complete the following information):**
 - Minecraft Version: 1.19.4
 - EMF version 0.2.5
 - ETF version 4.3.5

**Additional context**
Without FA the eyes are normal.

**Comment by ffuentesm** [comment]
The same goes for Sheep, dogs, and wolves
![image](https://user-images.githubusercontent.com/44974827/233803793-381c29e5-886c-45bd-b861-94033abdd671.png)
![image](https://user-images.githubusercontent.com/44974827/233803950-7724cff0-1f72-4f8e-b995-029dc24922dc.png)

**Comment by Traben-0** [comment]
Does it still happen with only etf and emf installed?

**Comment by ffuentesm** [comment]
no, with just those two it work. 
![image](https://user-images.githubusercontent.com/44974827/233804586-0c38c845-ca9b-48db-aaf2-312b7e8c6855.png)
![image](https://user-images.githubusercontent.com/44974827/233804600-7f9e0926-b72f-4491-9fbd-d9ed3d5c457b.png)

Strange that other mobs are not affected.

**Comment by Traben-0** [comment]
Weird, can you try and narrow down what mod caused the issue?

**Comment by ffuentesm** [comment]
The latest ETF update fixed the problem.
