### ISSUE TITLE
[Bug - models] Axolotl swims sideways (and sometimes backwards)

### ISSUE THREAD

**Issue by PixalThePixeled** [Traben-0/Entity_Model_Features#257]
The axolotl model is broken and sometimes faces the wrong way. This usually happens while they swims.

![2024-08-21_22 53 02](https://github.com/user-attachments/assets/fa2cee3f-5e0f-4e9a-b465-e3126382662d)
![2024-08-21_22 53 15](https://github.com/user-attachments/assets/501ff62e-8d56-4fe3-bc65-9f124dab2dcf)

 - Minecraft Version: 1.20.4
 - EMF version: 2.1.3, 2.2

**Comment by Traben-0** [comment]
what resourcepack are you using? does it work correctly in optifine?

**Comment by PixalThePixeled** [comment]
This happens without resource packs. This doesn't happen in optifine and vanilla.

**Comment by Traben-0** [comment]
can i get a screenshot of this happenign with only etf and emf loaded and no resourcepacks enabled?

**Comment by Traben-0** [comment]
just to confirm it is these mods by themselves doing it

**Comment by PixalThePixeled** [comment]
I checked all mods and found out that this bug appears with the Entity Culling mod along with ETM and EMF

**Comment by Traben-0** [comment]
> can i get a screenshot of this happenign with only etf and emf loaded and no resourcepacks enabled?

can i still get this with the entity culling mod as well

**Comment by PixalThePixeled** [comment]
I recorded a video

https://github.com/user-attachments/assets/5ac23cc1-9807-4b9f-b61f-17d9affc081c

At the same time, when I pull them out onto land, they return to their normal state, but after immersion in water they may again begin to swim unevenly (This may happen gradually over time).

**Comment by PixalThePixeled** [comment]
Last time when I tested Entity Culling without EMF and ETF they looked fine, but today it turned out that this is an Entity Culling issue and the bug appears without EMF and ETF, sorry for wasting your time.

**Comment by Traben-0** [comment]
I was just testing that lol, such an odd behaviour
