### ISSUE TITLE
[Bug - models] Newest version breaks some models

### ISSUE THREAD

**Issue by katubug** [Traben-0/Entity_Model_Features#263]
**Describe the bug**
On version 2.2, the models all show up fine. Once I upgrade to 2.2.2. or 2.2.3, my witches from Blue's Better Monsters get all jacked up.

**List and link to broken resourcepacks**
https://www.curseforge.com/minecraft/texture-packs/blues-better-monsters

**Expected behavior**
This is what it looks like with EMF 2.2.: https://i.imgur.com/B8Flw5S.png

**Screenshots**
And with the newer versions: https://i.imgur.com/P2QuvxM.png

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - EMF version: 2.2.2 and 2.2.23
 - ETF version: 6.2.2

**Comment by Traben-0** [comment]
can i get your game log

**Comment by katubug** [comment]
Yup, here ya go: https://gist.github.com/katubug/212b1ae2aee7d6f4c32cae0425410ac9

**Comment by VindSole** [comment]
Update broke my custom piglin models (normal, brute, zombie), oddly enough, all other models are fine.

**Comment by Traben-0** [comment]
> Update broke my custom piglin models (normal, brute, zombie), oddly enough, all other models are fine.

do they work in optifine?

**Comment by katubug** [comment]
I'm not the same person you're asking, but so far I've only seen the witch broken in my instance. I don't use optifine, though, so I can't say. But it works with previous emf

**Comment by VindSole** [comment]
I don't know as I do not use Optifine.

**Comment by Traben-0** [comment]
fixed for 2.2.4
