### ISSUE TITLE
[Bug - Vanilla Tweaks]

### ISSUE THREAD

**Issue by br1ghtmuff1n** [Traben-0/Entity_Model_Features#273]
**Describe the bug**
all zombies have the same texture. it works fine on optifine but doesn't work with emf and etf

**List and link to broken resourcepacks**
https://vanillatweaks.net/picker/resource-packs/

**Expected behavior**
What should it look like in OptiFine? screenshots?

**Screenshots**
![2024-09-26_00 05 05](https://github.com/user-attachments/assets/144ad017-5c61-4187-aa60-f78ac290df8f)

**(please complete the following information):**
 - Minecraft Version: 1.21
 - EMF version 2.2.6
 - ETF version 6.2.5

**Additional context**
the website said it should work

**Comment by Traben-0** [comment]
this is known, i've been misled about an optifine limitation and am going to resolve it, for now you can go to the EMF
 settings and 'optifine  settings' and disable the require base model setting

**Comment by br1ghtmuff1n** [comment]
sorry, i didnt know that you already knew. thanks for helping tho
