### ISSUE TITLE
Extreme lag caused by EMF

### ISSUE THREAD

**Issue by VaporeonScripts** [Traben-0/Entity_Model_Features#275]
**Describe the bug**
when im near villagers i lag alot, spark reports its caused by this mod, im using this mod cuz of fresh animation

![image](https://github.com/user-attachments/assets/5d7257ed-a101-4c49-a773-6e6047842aa2)

**Expected behavior**
lag alot
**Screenshots**
![image](https://github.com/user-attachments/assets/644f1c77-b6d5-4976-9032-d3f0542be9ac)

**(please complete the following information):**
 - Minecraft Version: 1.21.1
 - EMF version latest possible
 - ETF version latest possible

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/daae43b7-e64c-4e08-91f3-759f0429c7e6)

**Comment by VaporeonScripts** [comment]
https://spark.lucko.me/gMQP1QUtHu

**Comment by VaporeonScripts** [comment]
The observable got nothing to do with emf but the thread is still lagging due to the mod,causing massive fps lag

**Comment by Traben-0** [comment]
villagers are using only 6% of the render time, that seems pretty normal with FA, especially when staring directly at a meeting space with them all gathered

your fps also looks reasonable  with an avg of 142 with a min of 125?

can i get a comparison with FA off and another with EMF disabled

**Comment by Traben-0** [comment]
a single profile by itself is meaningless, without comparison, unless it was showing a truly ridiculous value

**Comment by Traben-0** [comment]
btw the reason the other mobs in the world are using so little render time by comparison is because you have entity culling culling them out, this just makes the villagers stand out even more than they would in vanilla

**Comment by VaporeonScripts** [comment]
closed as i fully deleted this mod as it just lags lol
