### ISSUE TITLE
[Bug] Crash or Compatibility

### ISSUE THREAD

**Issue by Silverbolt666** [Traben-0/Entity_Model_Features#286]
**Describe the bug**
Multiplayer and single player does not load with a modified skin loaded, leading to crash. Resetting the skin to not have any editions solves it.
Haven't been able to pin point the cause after several hours of troubleshooting.

**To Reproduce**
1. Having skin edited with EMF or ETF,
2. Try to join the singplayer world, or server, with the used modpack

**Expected behavior**
Being able to join the world. In multiplayer to either see the edited skin models made by other players. In singleplayer to join the world and play.

The issue does not occur on another modpack (if needed for further assessment please request)

[latest0.log](https://github.com/user-attachments/files/17624519/latest0.log)
[latest1.log](https://github.com/user-attachments/files/17624520/latest1.log)
[crash-2024-11-04_22.17.16-client.txt](https://github.com/user-attachments/files/17624521/crash-2024-11-04_22.17.16-client.txt)
[crash-2024-11-04_21.59.16-client.txt](https://github.com/user-attachments/files/17624522/crash-2024-11-04_21.59.16-client.txt)

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - EMF version 2.2.6
 - ETF version 6.2.5
 - Does the issue persist with only EMF installed?
 - [Modlist_With Error.txt](https://github.com/user-attachments/files/17624555/Modlist_With.Error.txt)
 - [Modlist Withouth Error.txt](https://github.com/user-attachments/files/17624556/Modlist.Withouth.Error.txt)

**Additional context**

Not frequently, but the game crashes on load with quark loaded. The crash report of such event is what follows:
[crash-2024-11-04_22.38.43-fml.txt](https://github.com/user-attachments/files/17624639/crash-2024-11-04_22.38.43-fml.txt)

Have modified the config files for both mods:
[entity_texture_features.json](https://github.com/user-attachments/files/17624581/entity_texture_features.json)
[entity_model_features.json](https://github.com/user-attachments/files/17624582/entity_model_features.json)

Loaded ResourcePacks on modpack without error:
- Better Cats
- Cubic Sun & Moon
- Fresh Animations
- More Mob Variants - Fresh Animations
- Night Sky Shader
- Fresh Moves

*Loaded ResourcePacks on Modpack with error:
 - Better Cats
 - Cubic Soon & Moon
 - Night Sky Shader

**Comment by Traben-0** [comment]
update ETF to 6.2.7 it was an issue with the new 3d skin layers mod update
