### ISSUE TITLE
[Bug] Incompatible with Sophisticated Backpacks

### ISSUE THREAD

**Issue by IranMine123** [Traben-0/Entity_Model_Features#289]
***DISCLAIMER: This is a duplicate of https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1223 issue. as the developer request, the issue is reposted on here.***

**Describe the bug**
Hello. it seems [Sophisticated Backpacks](https://github.com/P3pp3rF1y/SophisticatedBackpacks) mod is not compatible with [Entity Model Features (EMF)](https://github.com/Traben-0/Entity_Model_Features). the issue is I'm using a resource pack that makes player have better animation which handled by EMF. but the backpack is not get animated. here is a video:

https://github.com/user-attachments/assets/10fa9901-f18d-4910-aacb-611114c220d5

**To Reproduce**
1. Installing both Sophisticated Backpack & Core and EMF mod
2. Installing a player animation model resource pack (like [Expressive Fresh Moves](https://modrinth.com/resourcepack/tras-fresh-player))
3. doing F5 and backpack animation not synced with EMF

**Expected behavior**
Compatible with EMF, so I can see backpack is moving within the player's chest

**Versions**
Minecraft: 1.21.1 Fabric (I don't think its fixed on forge too)
Sophisticated Core: 0.6.50.61
Sophisticated Backpacks: 3.20.19.51
Entity Model Features (EMF): 2.2.2
Entity Texture Features (ETF): 6.2.2

**Comment by Traben-0** [comment]
note to self: possible mixin target detailed in linked issue

**Comment by IranMine123** [comment]
@Traben-0 sorry for mention but as you know the bug get fixed (https://github.com/P3pp3rF1y/SophisticatedBackpacks/commit/c86c72a6ff208cb9cb4c7e815495a75130c3976c) so im closing this
