### ISSUE TITLE
[Bug - models] Certain models appear weird

### ISSUE THREAD

**Issue by nenamoree9** [Traben-0/Entity_Model_Features#290]
The bug is when certain models, especially for things like pigs, or even the player are broken. The baby pig model has wide gaps in legs. For the player model, the player 2nd layer renders weirdly like it's deattached.

List:
Fresh Player Animations by Agente511: https://modrinth.com/resourcepack/fresh-player-animations
Fresh Animations by FreshLX: https://modrinth.com/resourcepack/fresh-animations/versions
Detailed Animations by Cymock: https://modrinth.com/resourcepack/detailed-animations
Bare Bones x Fresh Animations by Specimen: https://modrinth.com/resourcepack/bare-bones-x-fresh-animations

It should look normal and like it should, like the player 2nd layer is attached to player model and the baby pig'a legs are spaced correctly. Unfortuanetly I didn't provide screenshots :(

 - Minecraft Version: 1.21.3
 - EMF version: 2.3.0
 - ETF version: 6.2.8

**Comment by Traben-0** [comment]
#282

**Comment by Traben-0** [comment]
sorry i do realise the baby model animation issue wasn't actually mentioned in that doc, but i will add it now

**Comment by Traben-0** [comment]
Fresh needs to update his packs for 1.21.3

**Comment by nenamoree9** [comment]
i love the baby zombie
