### ISSUE TITLE
[Bug - models] My wolf models broke with an update

### ISSUE THREAD

**Issue by PastaLaPasta** [Traben-0/Entity_Model_Features#297]
**Describe the bug**
The custom wolf model I use, which worked in an earlier release, is now broken.

**List and link to broken resourcepacks**
https://drive.google.com/file/d/1U3BFLai65cVfrxJZHalez9BST09OqvkT/view?usp=sharing

**Expected behavior**
It looks the same in OptiFine as it does with EMF, apparently.

**Screenshots**
https://imgur.com/a/JzdG7Ni

**(please complete the following information):**
 - Minecraft Version: 1.21 (also tested in 1.21.1)
 - EMF version: 2.2.6

**Additional context**
I'm not even certain if the wolf model is being loaded at all to be honest. The texture is there, but the proportions of the body seems to match the vanilla body.
I don't recall what version of EMF was used, but earlier this year (I believe it was this August) I was making textures for the new wolf variants that was added recently, and back then the model worked like it was supposed to.

**Comment by Traben-0** [comment]
are there any errors in your log explaining why the model failed?
does it load in blockbench?

if its is identical in optifine then something msut be wrong with the model itself
