### ISSUE TITLE
[Bug - models] Broken models after the update

### ISSUE THREAD

**Issue by Thornecrous** [Traben-0/Entity_Model_Features#299]
**Describe the bug**
Broken models on some mobs with Fresh Animations, most are fine.
Noticed on: Zombie, Drowned (exactly same thing as zombies), Bogged, Enderman
Baby zombies and drowneds are weird.
Displacement of player's skin attachments in Fresh Moves.

Fresh Moves: Weird movement of player's skin attachments.

**List and link to broken resourcepacks**
I'm using Fresh Animations 1.9.2, the latest version
https://modrinth.com/resourcepack/fresh-animations
Fresh Moves, Expressive 3.0.1
https://modrinth.com/resourcepack/tras-fresh-player/versions

**Expected behavior**
Head and skin attachments should be where they usually are.

**Screenshots FA**
![image](https://github.com/user-attachments/assets/64e8a081-8d08-48b3-93c1-4a377629e551)
![image](https://github.com/user-attachments/assets/86a2ee86-7320-432e-ba7b-50973552c381)
![image](https://github.com/user-attachments/assets/f7399be4-df64-43f2-ba87-058c75b9c547)
![image](https://github.com/user-attachments/assets/5d3b7bc3-05bd-41a5-a180-1af76717b6be)

**Screenshots Fresh Moves**
![image](https://github.com/user-attachments/assets/33902ba7-2c90-48cd-9e3a-6747d0ea9da9)

**(please complete the following information):**
 - Minecraft Version: 1.21.4
 - EMF version: 2.3.0
 - ETF version: 6.2.9 (it works as intended)

**Additional context**

**Comment by Thornecrous** [comment]
please nevermind, didn't notice the warning

**Comment by the-Radek** [comment]
I have the same issues for FA 1.10.1. Can you provide what warning helped you fix these issues? Where can one find warnings for FA?

- Minecraft [1\.21\.10]
- Fresh Animations [1\.10\.1]
- AppleSkin [3\.0\.7\+mc1\.21\.9]
- Axiom [5\.1\.1]
- Better Mount HUD [1\.2\.6]
- Carpet Mod [1\.4\.188\+v251016]
- ChunkDebug [2\.5\.0\+1\.21\.9]
- Cloth Config v20 [20\.0\.149]
- Distant Horizons [2\.3\.6\-b]
- Dynamic FPS [3\.10\.1]
- Entity Model Features [3\.0\.5]
- Entity Texture Features [7\.0\.4]
- EntityCulling [1\.9\.3]
- EssentialClient [2\.3\.0\+1\.21\.9]
- Fabric API [0\.138\.3\+1\.21\.10]
- Fabric Language Kotlin [1\.13\.7\+kotlin\.2\.2\.21]
- FerriteCore [8\.0\.2]
- Iris [1\.9\.6\+mc1\.21\.9]
- Litematica [0\.24\.3]
- Lithium [0\.20\.0\+mc1\.21\.10]
- MaLiLib [0\.26\.3]
- MiniHUD [0\.37\.2]
- Mod Menu [16\.0\.0\-rc\.1]
- NotEnoughAnimations [1\.10\.6]
- Placeholder API [2\.8\.1\+1\.21\.10]
- Reese's Sodium Options [1\.8\.5\+mc1\.21\.9]
- Replay Mod [1\.21\.10\-2\.6\.24]
- ScalableLux [0\.1\.6\+fabric\.c25518a]
- Sodium [0\.7\.2\+mc1\.21\.10]
- Sodium Extra [0\.7\.0\+mc1\.21\.9]
- YetAnotherConfigLib [3\.8\.0\+1\.21\.9\-fabric]
