### ISSUE TITLE
[Idea] Upload to Modrinth

### ISSUE THREAD

**Issue by RoonMoonlight** [Traben-0/Entity_Model_Features#3]
**Is your feature request related to a problem? Please describe.**
I am the modpack creator from Modrinth, and there is no Modrinth release and would like to see it added.

**Describe the solution you'd like**
Publish this mod to Modrinth.

**Does OptiFine do this**
OptiFine does not matter with this feature request.

**Additional context**
Modrinth is the open-source and ease of use Modding platform for Minecraft: Java Edition. [See more details here.](https://modrinth.com)

**Comment by Timolino456** [comment]
It has already been uploaded to Modrinth, but it is yet to be approved (will probably happen today).

**Comment by RoonMoonlight** [comment]
Oh really? Thanks!
