### ISSUE TITLE
[Bug - models]  I disabled the lod but Animations continue to skipping keyframes  

### ISSUE THREAD

**Issue by Magiciandseq3** [Traben-0/Entity_Model_Features#307]
1.20.1
EMF 2.4.1
![image](https://github.com/user-attachments/assets/8af6106c-61b4-4096-b38b-499502bda10e)
  I disabled the lod but Animations continue to skipping keyframes  when 
 I go far away  from the entity and go back the animations play normal How I can fix this bug

**Comment by Traben-0** [comment]
I'm assuming this is the person who dm'd me and it was an unrelated issue with the wither storm distance entity??
