### ISSUE TITLE
[Bug] Crash or Compatibility 

### ISSUE THREAD

**Issue by TimoTe0** [Traben-0/Entity_Model_Features#309]
Bug description: aparently the game crashes when i use EMF with optifine

**To Reproduce**
Launch the game with these two mods in their folder

**Expected behavior**
To Work fine :S

**Screenshots**
![image](https://github.com/user-attachments/assets/d0ce09de-47b4-4661-87ae-e6dc09291f4a)

**Crashlog**
[crash-2024-12-23_12.32.36-client.txt](https://github.com/user-attachments/files/18231136/crash-2024-12-23_12.32.36-client.txt)

**(please complete the following information):**
 - Minecraft Version: [1.20.1]
 - EMF version [2.4.1]
 - Does the issue persist with only EMF installed?
 - No
 - if applicable, provide your modlist or log
Aquaculture-1.20.1-2.5.3
architectury-9.2.14-forge
backpacked-forge-1.20.1-2.2.5
balm-forge-1.20.1-7.3.10-all
bettervillage-forge-1.20.1-3.2.0
born_in_chaos_[Forge]1.20.1_1.5.2
caelus-forge-3.2.0+1.20.1
Craftable Elytra (1.20.1)
crittersandcompanions-forge-2.2.2
curios-forge-5.11.0+1.20.1
duclib-1.20-1.1.4
endertrigon-1.20.1-1.1-all
entity_model_features_forge_1.20.1-2.4.1
entity_texture_features_forge_1.20.1-6.2.9
FallingTree-1.20.1-4.3.4
framework-forge-1.20.1-0.7.12
geckolib-forge-1.20.1-4.4.9
gravestone-forge-1.20.1-1.0.24
ironchest-1.20.1-14.4.4
Jade-1.20.1-forge-11.11.1
jei-1.20.1-forge-15.17.0.74
justhammers-forge-2.0.4+mc1.20.1
libraryferret-forge-1.20.1-4.0.0
lootr-forge-1.20-0.7.35.90
luckys_armory-0.4.0.1-forge-1.20.1-BETA
minecraft-comes-alive-7.5.14+1.20.1-universal
mvs-4.2.6-1.21
OptiFine_1.20.1_HD_U_I6
origins-classes-forge-1.2.1
origins-forge-1.20.1-1.10.0.9-all
radiantgear-forge-2.1.5+1.20.1
recrafted_creatures-1.4.6-1.20.1
refurbished_furniture-forge-1.20.1-1.0.8
Ribbits-1.20.1-Forge-3.0.2
serversleep-mod
takesapillage-1.0.3-1.20.1
veinmining-forge-1.5.0+1.20.1
wardrobe-1.0.3.1-forge-1.20.1
waystones-forge-1.20-14.1.6
XaerosWorldMap_1.39.0_Forge_1.20
YungsApi-1.20-Forge-4.0.6
YungsBetterMineshafts-1.20-Forge-4.0.4

**Comment by Traben-0** [comment]
Yes emf and etf are not compatible with optifine as they are alternatives to optifine
