### ISSUE TITLE
[Bug - models] 9 Broken models found

### ISSUE THREAD

**Issue by Felina-Lain** [Traben-0/Entity_Model_Features#34]
Hello,
I saw the mod had updated, so I downloaded and went to test on a test world, using only Fresh Animations latest pack (1.8)
(f it can be of use here is the test world I used: https://www.planetminecraft.com/project/texture-testing-world-amp-zoo---browse-all-blocks-amp-mobs-easily/)

I then took list of every broken model I could find. I found 9 of them, listed below:
- both spiders have their limbs spread out
- both skeleton quivers (when using the addon for it) float above the skeleton
- The iron golem vines float above it
- Both donkeys with chest have two strange floating square on their sides, that move when they do
- The wandering trader has his little bags floating above his head
- The vex is the size of a zombie/illager, instead of being a tiny little bugger

Here some screenshots:
https://imgur.com/a/JWBBVPy

 - Minecraft Version: 1.19.4
 - EMF version 0.2.8
 - ETF version 4.4.0
 - EntityCulling 1.6.2
 - Iris version 1.6.1
 - Sodium version 0.4.10

(The lack of a working Optifine equivalent for Entity Models resources is the only reason I'm not going full sodium, so if you need any help to test stuff, I'm completely down, got a big interest in this mod. I'm not too good at coding, but I can test)
If you need any other info, ping me.

have a nice day!

**Comment by Traben-0** [comment]
Yes these are all issues with the addon pack which is listed as mouth fully working yet

Ps the vex should be fixed if you have the right version of fa 1.8 for 1.19.2 and 1.8.1 for 1.19.3+

**Comment by Traben-0** [comment]
If you want to help out check out the discord link on the readme

**Comment by Felina-Lain** [comment]
> Yes these are all issues with the addon pack which is listed as mouth fully working yet
> Ps the vex should be fixed if you have the right version of fa 1.8 for 1.19.2 and 1.8.1 for 1.19.3+

Ah, apologies, I didn't think to check if FA had updated too. I updated mine and indeed, the vex is now fine.
For the addon pack, I figured that was probably the case, not a priority which I totally get, but just thought a list of the bugs would still be useful to have? (I did see the old post about them, and some of the bugs of that post got solved but some didn't, but maybe I should have commented that post instead, apologies in that case.)

I joined the discord though, to see what's going on that I could help with!

**Comment by Traben-0** [comment]
Villager eyes will be a different issue, this issue is specifically issues with the FA addon pack, which should hopefully be fixed soon

**Comment by OrniiDiien** [comment]
Ah gotcha! Just a bit confused since when I was still using Optifine before switching to Fabric stuff FA addons worked just fine for me, with the exception of some really long mob blinking sometimes. In that case I can wait for fixes :]

**Comment by Traben-0** [comment]
these were fixed a few versions back, the addons still have some lighting glitches until etf next updates
