### ISSUE TITLE
[Idea] 1.18.2 Backport

### ISSUE THREAD

**Issue by Y1rd** [Traben-0/Entity_Model_Features#41]
**Is your feature request related to a problem? Please describe.**
When playing a 1.18.2 modpack (e.g. Better Minecraft, other Private Modpacks, etc) with [Entity Texture Features](https://modrinth.com/mod/entitytexturefeatures), and using [HIDYK's REALM](https://modrinth.com/resourcepack/hidyksrealm). I experience some broken entity textures due to incorrect models.

**Describe the solution you'd like**
It would be great for those still stuck on this version mainly (like me), to have a optifine alternative so we can use Rubidium and other mods for better performance and stability.

**Does OptiFine do this**
*Yes,* obviously.

**Additional context**
It may, or may not, be difficult to backport all the mod's features to 1.18.2. But I am not a Java developer, so I wouldn't know. I'm questioning if you are willing do it, respectfully, of course.

**Comment by Y1rd** [comment]
Was going to close this issue due to staleness, but it appears a backport is in progress. I'll keep this open.

**Comment by codemaster101-web** [comment]
ayyye I had no idea anybody also wanted compatibility with HIDYK. I think the zombie village pants are a bit broken and the new husks are weird using emf and etf. Do you mind hitting me up if there's some update?

**Comment by Traben-0** [comment]
this is planned, there is a buggy testing backport in my discord that isnt recommended for casual use

**Comment by Y1rd** [comment]
Bit late here, I'll check out the backport test a bit later.

**Comment by Y1rd** [comment]
The mod has been backported, I can see the release on [Modrinth](https://modrinth.com/mod/entity-model-features/versions?g=1.18.2) here. Closing as this is complete.
