### ISSUE TITLE
[Bug - models]Some models are broken with EMF

### ISSUE THREAD

**Issue by ghost** [Traben-0/Entity_Model_Features#43]
**Describe the bug**
This resourcepack works perfectly on vanilla but it will encounter some issues when working with EMF.These are all the broken models I have found so far.

**List and link to broken resourcepacks**
https://mizunomcmemo.blogspot.com/p/resourcepack.html

**Expected behavior**
On vanilla
![2023-05-10_15 37 07](https://github.com/Traben-0/Entity_Model_Features/assets/129179911/ad596300-7abd-45b3-b252-78f66fe044d0)
(Chicken,Mooshroom,Village,Cow,Pig,Sheep)

**Screenshots**
![2023-05-10_15 35 07](https://github.com/Traben-0/Entity_Model_Features/assets/129179911/d3d2314a-de1e-4148-9b41-393b790053cc)

**(please complete the following information):**
 - Minecraft Version: [1.19.2]
 - EMF version[0.2.8]
 - ETF version[4.4.4]

**Comment by Traben-0** [comment]
enabling the setting to subsittute missing model parts might help this

**Comment by marisgandara** [comment]
> enabling the setting to subsittute missing model parts might help this
> 
> I will eventually get that working in normal usage

I am having the same issue. I enabled the setting mentioned and it "worked" but there's a weird floating piece above the cows 
![2023-06-28_11 32 44](https://github.com/Traben-0/Entity_Model_Features/assets/118464243/98897995-5424-4e46-9f02-2f2a11bf13f7)
