### ISSUE TITLE
[Bug - models] Missing Zombie Model of CMMRP texture pack

### ISSUE THREAD

**Issue by KiyooChan** [Traben-0/Entity_Model_Features#46]
**Describe the bug**
Zombie model is lost when CMMRP installed.

**List and link to broken resourcepacks**
https://www.curseforge.com/minecraft/texture-packs/cute-mob-models-resource-pack

**Expected behavior**
It should be the same model just like husk, which display correctly under EMF mod.
https://imgur.com/KG1h5zr

**Screenshots**
When using EMF mod, the zombie seems to use the vanilla model rather than the CMMRP one, meanwhile the husk, and all the other mobs are using the correct models
https://imgur.com/x2YtjlH

**(please complete the following information):**
 - Minecraft Version: 1.19.2
 - EMF version 0.2.9
 - ETF version 4.4.4

**Additional context**
I just don't understand why zombie excluded. I've checked its .jem file and texture, compared with the husk, didn't see any trail.

**Comment by KiyooChan** [comment]
Update, the issue can be solved by restart the game process, but it did reproduce sometimes.

**Comment by Totomio** [comment]
Minecraft Version: 1.19.2
EMF version 0.2.9
ETF version 4.4.4

i have a similar issue with vanilla texture and FA 1.8, the zombie is the only non-animated mob
