### ISSUE TITLE
[Bug - models] Mob textures broken, but inconsistent of what mobs are broken at the time

### ISSUE THREAD

**Issue by Seralii** [Traben-0/Entity_Model_Features#48]
**Describe the bug**
Some textures are broken on the models. It seems to alternate what models are broken, like sometimes the wolf texture is broken, sometimes the horse and sheep textures are broken. Most times it seems like the sheep, horses, and wolves are broken altogether. Spider is indefinitely broken, have not been able to fix those textures. Seems like when I relog into Minecraft that different mobs textures break.  I disabled Quark's animal variants and it fixed the pigs, chickens and cows. I tried enabling a setting in the EMF config that was recommended in another bug report, did not work. I am using All The Mods 8. Weirdly, when I very first installed EMF and ETF, all the models except for spider were working (perhaps beginners luck? lol). After that, have not been able to have the textures working.

**List and link to broken resourcepacks**
Patrix x64, Patreon exclusive I don't have the link.
**Expected behavior**
What should it look like in OptiFine? screenshots?
Using Rubidium version 0.6.2a, ETF, EMF, Forge 43.2.11. I don't have Optifine screenshots. 
**Screenshots**

![2023-05-19_00 14 21](https://github.com/Traben-0/Entity_Model_Features/assets/62581193/177246e5-24cc-4919-80b6-e7862eae4f8d)
![2023-05-19_00 14 29](https://github.com/Traben-0/Entity_Model_Features/assets/62581193/faed9229-cfd9-42e1-b462-7c15904e888d)
![2023-05-19_00 14 43](https://github.com/Traben-0/Entity_Model_Features/assets/62581193/27153882-ffc2-4b8f-b657-bd9a70b2eb9c)
![2023-05-19_00 14 51](https://github.com/Traben-0/Entity_Model_Features/assets/62581193/d10dc07e-bd5f-4dde-b196-ccda7d52b87c)

**(please complete the following information):**
 - Minecraft Version: 1.19.2
 - EMF version 0.2.9
 - ETF version 4.4.4

**Comment by Dirt-Eater** [comment]
I've been having the same inconsistent visual glitches but only with a handful of mobs added by mods, namely the skeleton creeper from graveyards, the vampire illager from supernatural, and the archer and legionnaire from it takes a pillage. Seems to be random as in some of my tests only the skeleton is broken, sometimes the archer, sometimes the archer and the legionnaire, sometimes just the legionnaire, sometimes the vampire. Very strange, hoping there's a fix of some kind as this mod is required for Max's better mobs but the mobs it's breaking are some that I really like and don't want to get rid of.

**Comment by Traben-0** [comment]
what version of EMF are you using?
