### ISSUE TITLE
Bug? - Unhandled solver error with quilt.

### ISSUE THREAD

**Issue by JaxHendricks** [Traben-0/Entity_Model_Features#49]
I get a crash whenever I add CEM in with this mod, but as soon as I remove CEM it stops throwing a unhandled solver error and boots minecraft perfectly fine.

Not sure how to proceed with diagnosing this, but here is my crashlog: 
[crash-2023-05-20_14.06.43.8443-quilt_loader.txt](https://github.com/Traben-0/Entity_Model_Features/files/11522915/crash-2023-05-20_14.06.43.8443-quilt_loader.txt)

**Comment by Timolino456** [comment]
Delete CEM, you don't need it when using EMF.

**Comment by Traben-0** [comment]
Cem is listed as incompatible and thus they both cannot load together, i guess quilt crashes in these cases which sounds like a weird way to handle it

Fabric will give you a warning screen and explain the issue

**Comment by JaxHendricks** [comment]
Hm. Alrighty. Thank you.

For some reason the fork I'm using of CEM said that ETF would "expand the capabilities of CEM" and never said the two were incompatible. Guess I should've done a tiny bit more of research.

Thanks for clarifying though!

Fork of CEM: https://github.com/YoungSoulluoS/cemFork

**Comment by Traben-0** [comment]
ETF is compatible with cem, but EMF is not, they are two different mods
