### ISSUE TITLE
[Bug - models] Vexes are way too large

### ISSUE THREAD

**Issue by App4ri** [Traben-0/Entity_Model_Features#5]
**Describe the bug**
The vex model for the fresh animations resource pack is way too large

**List and link to broken resourcepacks**
"Fresh animations" and "bare bones x fresh animations"

**Expected behavior**
Vex models shouldn't be as large as players

**Screenshots**
![2023-04-02_17 27 40_edited](https://user-images.githubusercontent.com/125201193/229382482-f611e797-b9c2-4d5f-8c4d-3d7787bfb643.png)

**(please complete the following information):**
 - Minecraft Version: 1.19.3
 - EMF version: 0.2.4
 - ETF version if applicable: 4.3.3

**Additional context**
N/A

**Comment by Traben-0** [comment]
Hi Appri4ri, this is actually an issue with Fresh animations as it hasn't adapted to the vex model changing in 1.19.3 compared to 1.19.2. It should work better in 1.19.2 :)
