### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by EggysTheboi** [Traben-0/Entity_Model_Features#53]
In the fabric launcher whenever I run minecraft it says cannot run with any version of Cem, I do not know how to fix this. This says "Mod 'Entity Model Features' (entity_model_features) 0.2.9 is incompatible with any version of mod 'Custom Entity Models' (Cem), but matching versions are present: 0.7.3-1.19/0.7.1_S7_1.19!"

**Comment by YoungSoulluoS** [comment]
Use only EMF Just use EMF and that's it

**Comment by Traben-0** [comment]
EMF and CEM do the same thing but differently

you must pick one or the other, I ofcourse recommend EMF
