### ISSUE TITLE
[Bug] 'Resource Load Failed' when using "Barely Default" by Mickey Joe

### ISSUE THREAD

**Issue by ShroomiePerson** [Traben-0/Entity_Model_Features#54]
**Describe the bug**
I'm trying to use "Barely Default" by Mickey Joe

**To Reproduce**
install ETF and EMF, install Barely Default, put BD in your Resource Pack folder, and try to load the mod. The resource pack *does* load once the loading screen is done, but it instantly goes back into a loading screen and in the top right corner a banner pops up saying Resource Load Failed.

**Expected Behavior**
the resourcepack is expected to load, but doesn't

**Crashlog**
here's my latest.log
https://mclo.gs/NYZwqam

**(please complete the following information):**
 - Minecraft Version: 1.19.3
 - EMF version: 0.2.9
 - ETF version: 4.4.4
 - Does the issue persist with only EMF installed? Yes, kinda. this version doesn't work without ETF, but when loading the resource pack with only ETF it loads.

**Additional context**
my modpack *probably* doesn't matter because i started a new instance with the same Minecraft and Quilt version without any other mods than ETF and EMF, then i try to load Barely Default, and i get the same error.

**Comment by ShroomiePerson** [comment]
hello?

**Comment by Traben-0** [comment]
Hey it's something crashing with the horse model,  can you try it with the latest version
