### ISSUE TITLE
[Bug] if() functions don't work in other if()

### ISSUE THREAD

**Issue by JonnyBro** [Traben-0/Entity_Model_Features#56]
**Describe the bug**
Title says it all

**To Reproduce**
Download my latest player animations resourcepack
[click](https://cdn.discordapp.com/attachments/951714496714530826/1102325548572753960/Vanilla_Player_Models.zip)

![image](https://github.com/Traben-0/Entity_Model_Features/assets/48434875/c04e1fe5-f7be-412c-b168-868fb2a15a06)

**Expected behavior**
![image](https://github.com/Traben-0/Entity_Model_Features/assets/48434875/cd0af868-7994-44a0-a17b-d85ea8396fba)

 - Minecraft Version - 1.19.4
 - EMF version - 0.2.4
 - Does the issue persist with only EMF installed? **Yes**

**Comment by Traben-0** [comment]
identified the issue, will be in the next release and first 1.20 build
