### ISSUE TITLE
[Bug - models]  Two models of a wolf appear overlapping each other 

### ISSUE THREAD

**Issue by Naanachi** [Traben-0/Entity_Model_Features#57]
on 1.19.2, farbric using EMF 0.2.9 and ETF 4.4.4
The wolf should look like and be animated like this pig, but instead the vanilla's wolf model overlaps with the resourcepack , tried removing all my other mods to see if something was causing that but issue still persist 

Im using this exact version of the resourcepack
https://www.curseforge.com/minecraft/texture-packs/fresh-animations/files/4360370

![image](https://github.com/Traben-0/Entity_Model_Features/assets/85463975/fa6f3db3-a2a1-4d1b-a321-2a17db19e10d)
https://github.com/Traben-0/Entity_Model_Features/assets/85463975/4de67faf-6b65-4229-b285-436099feefe5

**Comment by ffuentesm** [comment]
I have the same problem in 1.20.1 Forge
EMF: entity_model_features_forge_1.20-0.2.11
ETF: entity_texture_features_forge_1.20-4.4.5
![image](https://github.com/Traben-0/Entity_Model_Features/assets/44974827/f7388dc2-65c9-41e6-b2d2-d31e378a4c75)

**Comment by Traben-0** [comment]
do you have the setting to subsitiute missing model parts enabled?
this can happen when it is as that code is not final yet

**Comment by ffuentesm** [comment]
I have not touched the mod settings. 
I just installed both EMF and ETF as they are.

**Comment by Mulinix** [comment]
Same issue here. v1.19.2-Fabric
Wolves original model overlaps the animated one.
Sheep wool is misplaced, looks like it floats above the body.  
And I'm not sure if intended, but cat's tails seem to be doubled and draw over each other while standing and walking. 
Everything else so far is on point, so I'll suffer through these eerie creatures for now.

![2023-07-17_15 38 24](https://github.com/Traben-0/Entity_Model_Features/assets/46545016/8e5f9d65-ed57-4614-9ed7-6e250be89098)
![2023-07-17_15 39 02](https://github.com/Traben-0/Entity_Model_Features/assets/46545016/01ed80d8-ed13-44fc-bed8-e3b3bab3b814)
![2023-07-17_15 48 29](https://github.com/Traben-0/Entity_Model_Features/assets/46545016/2950edb9-28bb-4286-8f1c-7ede490e58ce)
![2023-07-17_15 49 31](https://github.com/Traben-0/Entity_Model_Features/assets/46545016/6f94e170-c4f3-468d-8274-1091517b39d9)
