### ISSUE TITLE
[Bug - models]snow fox renders abnormally while Fresh Animations v1.8 used

### ISSUE THREAD

**Issue by Miaochan** [Traben-0/Entity_Model_Features#6]
**Describe the bug**
rendering issue about snow fox

**List and link to broken resourcepacks**
https://www.curseforge.com/minecraft/texture-packs/fresh-animations

**Expected behavior**
none.

**Screenshots**
![Screenshot01](https://user-images.githubusercontent.com/129179911/229585079-64c1ee47-dabf-497a-9f6b-464de262cbe8.png)

**(please complete the following information):**
 - Minecraft Version: [1.19.2-Forge_43.2.3]
 - EMF version[0.2.4]
 - ETF version if applicable [4.3.3]

**Additional context**

**Comment by Wooferscoots** [comment]
This is a fresh animations bug. The eyes were left out of the snow fox texture.

**Comment by Miaochan** [comment]
> This is a fresh animations bug. The eyes were left out of the snow fox texture.

got it
