### ISSUE TITLE
[Bug - models] Chest rendering issue with EMF & Chests Reimagined

### ISSUE THREAD

**Issue by Combeez** [Traben-0/Entity_Model_Features#61]
**Describe the bug**
When using EMF with Chests Reimagined chests sometimes render incorrectly

**List and link to broken resourcepacks**
https://www.curseforge.com/minecraft/texture-packs/chests-reimagined

**Expected behavior**
https://imgur.com/a/dro2u1g

**Screenshots**
https://imgur.com/a/6XzUC3G

**(please complete the following information):**
 - Minecraft Version: 1.20
 - EMF version 0.2.10
 - ETF version 4.4.4

**Additional context**
The problem is inconsistent, with single or double chests/trapped chests and/or ender chests each seemingly randomly either being normal or incorrect, and changing on restart of the game.

**Comment by Vulcagon** [comment]
I have the same problem with faithfuls Chest 3D addon which works with Optifine but with EMF the chests render incorrectly.

Resource Pack:
https://faithfulpack.net/addons/chest3Doptifine

Minecraft version: 1.20.1
EMF version: 0.2.13
ETF version: 4.4.4

**Comment by Traben-0** [comment]
Chests aren't properly supported yet, they should be in the next update
