### ISSUE TITLE
[Bug - models] Spiders are always broken when using the fresh animations extensions

### ISSUE THREAD

**Issue by NolanHewitt** [Traben-0/Entity_Model_Features#65]
Describe the bug
Spiders are always broken when using the fresh animations extensions.

List and link to broken resourcepacks
https://www.curseforge.com/minecraft/texture-packs/fresh-animations
https://www.curseforge.com/minecraft/texture-packs/fresh-animations-extensions

Screenshots
<img width="1280" alt="Minecraft Screenshot 2023 06 24 - 22 36 02 24" src="https://github.com/Traben-0/Entity_Model_Features/assets/52480898/6dffe666-2210-48f9-b350-c323b457c642">

Minecraft Version: 1.19.2
EMF version: 0.2.9
ETF version: 4.4.4

**Comment by Traben-0** [comment]
Does using EMF 0.2.12 with all its default settings fix this?

**Comment by NolanHewitt** [comment]
Yes! Spiders and Slimes are fixed, although it seems something broke sheep. 
![huge_2023-07-12_08 24 40-min](https://github.com/Traben-0/Entity_Model_Features/assets/52480898/d9633d92-8ab9-41a7-b017-51ccf9c8f6cc)

**Comment by NolanHewitt** [comment]
I've checked through all vanilla mobs, only the sheep and the vex have issues for me now.
