### ISSUE TITLE
[Bug - models] Trident Not Working

### ISSUE THREAD

**Issue by LordEnder-Kitty** [Traben-0/Entity_Model_Features#66]
**Describe the bug**
Tridents don't render when held and it uses the default model.

**List and link to broken resourcepacks**
[Rethoughted+Trident.zip](https://github.com/Traben-0/Entity_Model_Features/files/11860995/Rethoughted%2BTrident.zip)

**Expected behavior**
in optifine there's a little thing on the bottom of the trident 

**Screenshots**
![2023-06-25_16 55 37](https://github.com/Traben-0/Entity_Model_Features/assets/105356927/b4d45e91-eea9-4ca4-b55f-282091d9d558)

![2023-06-25_16 57 59](https://github.com/Traben-0/Entity_Model_Features/assets/105356927/43dcdc29-82e9-449f-9e7e-febeda6ab99b)

holding the trident
![2023-06-25_17 11 07](https://github.com/Traben-0/Entity_Model_Features/assets/105356927/a2f57800-5c41-4a16-836e-011f24391915)

 - Minecraft Version: fabric-loader-0.14.21-1.20.1
 - EMF 0.2.11
 - ETF 4.4.4

**Comment by SlightlyPeckish** [comment]
Also having the issue I hope it gets fixed too

**Comment by LordEnder-Kitty** [comment]
has this been fixed yet?

**Comment by 444aidan** [comment]
Still nothing on this? I'm also trying to use a custom trident model.

**Comment by Traben-0** [comment]
![2023-09-16_12 15 04](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/24f59f96-8337-4f27-8987-f3d7e3420791)
this is the template custom trident model working in EMF 1.0

is your pack not working in EMF 1.0? can you link me it?

**Comment by Traben-0** [comment]
#114
