### ISSUE TITLE
[Bug - models]Sometimes zombies or skeletons lose their animations

### ISSUE THREAD

**Issue by Staticlp** [Traben-0/Entity_Model_Features#7]
**List and link to broken resourcepacks**
https://www.curseforge.com/minecraft/texture-packs/fresh-animations/

**Screenshots**
![2023-04-04_02 04 28](https://user-images.githubusercontent.com/129179911/229591565-942c06bd-62a3-4497-86fd-b06bd9855be0.png)

**(please complete the following information):**
 - Minecraft Version: [1.19.2-Forge_43.2.3]
 - EMF version[0.2.4]
 - ETF version[4.3.3]

**Additional context**
[log.txt](https://github.com/Traben-0/Entity_Model_Features/files/11141202/log.txt)

**Comment by Traben-0** [comment]
Does it work and then break, or just produced not with at all?

Can I see your mod list

**Comment by Miaochan** [comment]
This problem only appears in my modpack.It will take a moment to narrow the scope of problem.I will reply as soon as possible

**Comment by Miaochan** [comment]
After my testing,Twilight forest may cause it.Occasionally,restart the game can solve this problem.
Mod list(3mods):
twilightforest-1.19.2-4.2.1518-universal.jar
entity_model_features_forge_1.19.2-0.2.4.jar
entity_texture_features_forge_1.19.2-4.3.3.jar
[latest.log](https://github.com/Traben-0/Entity_Model_Features/files/11144894/latest.log)

**Comment by Miaochan** [comment]
> Does it work and then break, or just produced not with at all?
> latter

**Comment by Miaochan** [comment]
Quark can make skeletons abnormal sometimes.
![2023-04-04_13 51 54](https://user-images.githubusercontent.com/129179911/229699931-5ee7c3cf-9ae9-4824-b1b2-db3f93bb8a84.png)
Mod list(4mods)
entity_model_features_forge_1.19.2-0.2.4.jar
entity_texture_features_forge_1.19.2-4.3.3.jar
AutoRegLib-1.8.2-55.jar
Quark-3.4-396.jar
[latest.log](https://github.com/Traben-0/Entity_Model_Features/files/11145151/latest.log)

**Comment by Miaochan** [comment]
[Vinery](https://www.curseforge.com/minecraft/mc-mods/lets-do-wine) makes wandering trader's eyes disappear lol
![2023-04-04_15 16 39](https://user-images.githubusercontent.com/129179911/229717503-bf109f8c-fbc5-4b2c-94fd-2343885efb6f.png)
Mod list(4 mods)
entity_model_features_forge_1.19.2-0.2.4.jar
entity_texture_features_forge_1.19.2-4.3.3.jar
vinery-1.19.2-1.1.7.jar
geckolib-forge-1.19-3.1.40


I only found those bugs.Shall I create a new issue if I found a new one?

**Comment by Traben-0** [comment]
seperate issues are preferred but these are good here

**Comment by Traben-0** [comment]
the logs do not detail the issues however I have some ideas, this will probably be fixed in future with another change I'm planning

**Comment by Traben-0** [comment]
can someone verify this with 0.2.12 default settings

**Comment by milkembers** [comment]
hey, i am also having this problem. some FA animations are applying randomly - it seems that every time i launch the game, a handful of them don't work. some of the ones that have been on/off are regular zombies, regular skeletons, creepers and tamed wolves. i don't think i've seen endermen working at all yet.

when i have some time tomorrow i'll comb through my modpack to see what mod is causing the issue, and i'll edit this. i do know i'm not using the mods that others listed above, except for Supplementaries.

Minecraft version: 1.20.1
Forge version: 47.1.0
EMF version 0.2.13
ETF version 4.4.5

**Comment by SaltSouls** [comment]
I can confirm that enderman are entirely broken in 1.19. Though for some reason the 1.20 version of the mod has them working. Not sure what is potentially causing this issue.

**Comment by Traben-0** [comment]
what mods are interacting here?

**Comment by Traben-0** [comment]
I would very much appreciate new info such as your mod list or any suspected mods you can narrow down for me, 

EMF 1.0 is so very different to the beta half of the things in this issue thread alone are completely irrelevant to 1.0 now

**Comment by Traben-0** [comment]
Yes list them

**Comment by Traben-0** [comment]
I highly suspect modern fix.
I will look into it properly when I get time

**Comment by Traben-0** [comment]
![2023-09-16_15 20 48](https://github.com/Traben-0/Entity_Model_Features/assets/8456487/89e9cc9e-15ee-4e10-bb13-6b843a97ccbe)
I can replicate it now with 1.19.2 modern fix on forge, i'll see what i can do

**Comment by Traben-0** [comment]
it is in fact not modernfix, theres something wrong with resource reloads, but not the first load, in forge 1.19.2 & 1.29.3

i will be moving this issue
