### ISSUE TITLE
Crash when loading game with shaders turned on

### ISSUE THREAD

**Issue by AlfmanOO7** [Traben-0/Entity_Model_Features#78]
**Describe the bug**

**To Reproduce**
1. open mc with shaders active
2. load cod
3. crash

**Expected behavior**
not to crash

**Screenshots**
N/A

**Crashlog**
https://mclo.gs/ZgTEm3q

**(please complete the following information):**
 - Minecraft Version: 1.19.4
 - EMF version 0.2.12
 - No, only occurs when loading mc with shaders active
 - Mods:
- 3D Skin Layers
- Adaptive Tooltips
- AdvancementInfo
- AdvancementPlaques
- Ambient Sounds
- Animatica
- Appleskin
- Architectury
- Armor Chroma for Fabric
- AuthMe
- Auto Clicker
- Better F3
- Better Mount HUD
- Better Ping Display
- Better Statistics Screen
- Blur
- Bobby 
- Borderless Mining
- Camera Overhaul
- Camera Utils
- Chat Heads
- Chat Patches
- CITResewn
- Client Side Noteblocks
- Cloth Config
- Colorful Hearts
- Colorful Subtitles
- Colour My Servers
- Complete Config
- Continue (Button)
- Continuity
- CreativeCore
- Dark Loading Screen
- Death Log
- Do a Barrel Roll
- Durability Notifier
- Dynamic App Icon
- Dynamic Crosshair
- Dynamic Sound Filters
- Eating Animation
- EnhancedVisuals
- Entity Culling
- Entity Model Features
- Entity Texture Features
- Equipemt Compare
- Fabric Carpet
- Fabric Language Kotlin
- Falling Leaves
- FerriteCore
- First Person Model
- Forge Config API Port
- Fuel Info
- Iceberg
- Indium
- Inspecio
- Inventory HUD+
- Iris (Shaders)
- Item Borders
- Item Scroller
- Item Swapper
- LambDynamicLights
- Legendary Tooltips
- Litematica
- Lithium
- Make Bubbles Pop
- MaLiLib
- Mambience
- MemoryLeakFix
- Minihud
- Mixin Trace
- Mod Menu
- NBT Autocomplete
- Not Enough Animations
- OptiGUI
- oωo (owo-lib)
- Physics Mod
- Presence Footsteps
- Prism
- Quilted Fabric API & Quilt Standard Libraries
- Reese's Sodium Options
- Remote Players
- Replay Mod
- Satin API
- Seamless
- ShulkerPick
- ShulkerboxTooltip
- Simple Shulker Preview
- SmoothBoot
- SmoothSwapping
- Sodium Extra
- Sodium Fabric
- Spyglass Astronomy
- Starlight
- Stendhal
- Tiny Item Animations
- Travellers Toasts
- Tweakeroo
- Visuality
- Void Fog
- Wavey Capes
- Xaero's Minimap
- Xaero's World Map
- Yet Another Config Lib
- Zoomify

**Additional context**
turning on shaders while in-game does not cause crashes, and any subsequent relogs don't cause crashes

**Comment by Traben-0** [comment]
I'm aware of this, there will be a patch soon

**Comment by SiverDX** [comment]
For me it crashes when a wandering trader is being rendered
Same problem with `IndexOutOfBoundException` etc. so I guess its just part of this issue

**Comment by Traben-0** [comment]
fixed in 0.2.13
