### ISSUE TITLE
[Bug - models] Some issues I found so far

### ISSUE THREAD

**Issue by JonnyBro** [Traben-0/Entity_Model_Features#8]
**Describe the bug**
Hi! Love your mods, and wanted to help. This some things I found while playing.
I didn't listed some mobs that already known (frog for example).

**List and link to broken resourcepacks**
[Fresh Animations 1.8](https://www.curseforge.com/minecraft/texture-packs/fresh-animations/)
[FA All Extensions 1.0](https://www.curseforge.com/minecraft/texture-packs/fresh-animations-extensions/)

**Screenshots**
<details>
<summary>Click to open</summary>

![image](https://user-images.githubusercontent.com/48434875/229796977-a6715f3d-2222-49ba-9639-bdea2e23e185.png)
![image](https://user-images.githubusercontent.com/48434875/229798311-219a7144-6edf-465d-af3b-cf2d0f0e14f9.png)
![image](https://user-images.githubusercontent.com/48434875/229798634-04fef474-e06d-45f4-b38f-57d748522a1b.png)
![image](https://user-images.githubusercontent.com/48434875/229798827-baf225b7-ea14-42b5-8734-1a670be7ac67.png)
![image](https://user-images.githubusercontent.com/48434875/229798894-f5d2bf5a-51c1-4bd9-95fa-07fd21f3319b.png)
![image](https://user-images.githubusercontent.com/48434875/229799378-4e4ebf9f-aee4-4045-b3dd-2cf893febb3a.png)
![image](https://user-images.githubusercontent.com/48434875/230072752-f2295839-cd70-4c15-bd82-a59f36b6d233.png)

</details>

UPD: Removed Vex's screenshot, found out it's a FA problem.
UPD2: Added Enderman

**(please complete the following information):**
 - Minecraft Version: 1.19.3
 - EMF version: 0.2.4
 - ETF version: 4.3.3

**Additional context**
If "All Extensions" are disabled, everything is fine.

**Comment by Traben-0** [comment]
Yes the extensions are a bit busted, thanks for the list and screenshots it will be very helpful

The animated player resource pack can be found in my discord I didn't link it because it is quite cursed at times as it doesn't have correct pivot points

**Comment by Traben-0** [comment]
https://discord.gg/rURmwrzUcz

**Comment by JonnyBro** [comment]
Added enderman to screenshots
