### ISSUE TITLE
[Bug - models] Disjointed bat ear with "No Z-fighting" resource pack

### ISSUE THREAD

**Issue by Mabra51** [Traben-0/Entity_Model_Features#80]
Bats have their left ear floating half a block above them when using this "no z-fighting" resource pack alongside EMF.

https://www.curseforge.com/minecraft/texture-packs/no-z-fighting

![2023-07-14_16 19 30](https://github.com/Traben-0/Entity_Model_Features/assets/12016338/94f820af-03b9-4c29-80c7-db5b35d5290c)

 - Minecraft Version: 1.19.2
 - EMF version: 0.2.13
 - ETF version: 4.4.4

**Comment by Traben-0** [comment]
This is an issue I am aware of and affects all default style bat models
