### ISSUE TITLE
[Bug - models] Problems with Fresh Animations Extensions. Weird minecart, chest and spiders

### ISSUE THREAD

**Issue by icynstant** [Traben-0/Entity_Model_Features#81]
Minecart and minecart with chest (may be others too) falls 1 block down under rail (screenshot). I was having problem with chest also, it was visualy half block to the left and in inventory too (trap chest and ender chest is fine), but it somehow fixed itself when i was removing my mods to find why i got this issues. Also i got problems with spiders and cave spiders, they aren't all red when i hit them (screenshot)

Last few days I updated your mod and resource pack to new version so im not sure that it's you made something wrong

Fresh Animations Extensions - All Extensions 1.2
https://www.curseforge.com/minecraft/texture-packs/fresh-animations-extensions

![2023-07-15_00 21 09](https://github.com/Traben-0/Entity_Model_Features/assets/127024748/547e7d60-56a1-429f-9718-e3b710d38199)
![2023-07-15_00 30 41](https://github.com/Traben-0/Entity_Model_Features/assets/127024748/aa5c2b9e-709e-43c3-9e1b-cccb13ab72e0)

 - Minecraft 1.20.1
 - EMF 1.20-0.2.13
 - ETF 1.20-4.4.4

**Comment by FLAC023** [comment]
To add to this bug report: I am using a version of NewDefault+ for 1.20.1 and I'm having similar issues. My assumption is that these aren’t exactly up to date to the models used in the current CEM feature in Optifine. Then again this is a shot in the dark
![2023-07-14_18 56 00](https://github.com/Traben-0/Entity_Model_Features/assets/84736168/a39ae5bd-0c53-4ba1-bf06-ca0d8b4630ec)
