### ISSUE TITLE
[Bug - models] Pig in Mizunos is broken

### ISSUE THREAD

**Issue by Ryuushen** [Traben-0/Entity_Model_Features#83]
Pigs model is broken for Mizunos JE if I turn on "Substitute missing model part" it still look like a pig but with the ear flying around
![javaw_HZZud68SZB](https://github.com/Traben-0/Entity_Model_Features/assets/24853902/d10ffc6e-a43c-4d4e-a4b3-cc311064bebd)

![javaw_yxJliGjcew](https://github.com/Traben-0/Entity_Model_Features/assets/24853902/b98a9018-45b7-4425-8b17-ae4060455b91)

**(please complete the following information):**
 - Minecraft Version: 1.19.2
 - EMF version: 0.2.13
 - ETF version: 4.4.4

**Comment by Ryuushen** [comment]
If I turn OFF "Try to prevent EMF models being overridden: " it fixes the issue regardless of the "Substitute missing model parts"

**Comment by terzag** [comment]
I have several issues with EMF and [Mizuno's texture pack](https://mizunomcmemo.blogspot.com/p/resourcepack.html) too. From what I've seen, pigs, cows and iron golems have issues (there might be other mobs I haven't noticed yet). In every case, by default the body is missing and some parts that are not part of the original model −although this might be a bug and they're supposed to be there?− appear above the mob. When setting the option to replace the missing parts of the model to yes, the body reappears but the extra floating parts are still there.

- the extra parts for the pig are the ears and maybe a saddle when equipped;
- the extra parts for the cow are the ears and mouth
- the extra parts for the iron golem are some kind of helmet/armour and arms

In my case, setting "Try to prevent EMF models being overridden" to no doesn't change anything.

It's worth noting that the armour of the golem doesn't appear when the mod isn't installed. I don't know how these model features work, I assume they're extra parts displayed only when using Optifine or equivalent but not on vanilla?

I've put pictures for the golem there: https://imgur.com/a/GOH2JCL
The first one is with default options (body missing, extra armour parts/arms floating), the second one is with the option to replace the missing parts (body reappears, extra parts still float).

Minecraft 1.20.1 with Fabric + Iris (and several mods/resources packs).

**Comment by Ryuushen** [comment]
> I have several issues with EMF and [Mizuno's texture pack](https://mizunomcmemo.blogspot.com/p/resourcepack.html) too. From what I've seen, pigs, cows and iron golems have issues (there might be other mobs I haven't noticed yet). In every case, by default the body is missing and some parts that are not part of the original model −although this might be a bug and they're supposed to be there?− appear above the mob. When setting the option to replace the missing parts of the model to yes, the body reappears but the extra floating parts are still there.
> 
> * the extra parts for the pig are the ears and maybe a saddle when equipped;
> * the extra parts for the cow are the ears and mouth
> * the extra parts for the iron golem are some kind of helmet/armour and arms
> 
> In my case, setting "Try to prevent EMF models being overridden" to no doesn't change anything.
> 
> I've put pictures for the golem there: https://imgur.com/a/GOH2JCL The first one is with default options (body missing, extra armour parts/arms floating), the second one is with the option to replace the missing parts (body reappears, extra parts still float).
> 
> Minecraft 1.20.1 with Fabric + Iris (and several mods/resources packs).

Just curious but I just found a temp solution i guess. I dont know if it applies to you but I had the mod "Better animation collection" and once i remove it all model seems to works fine. You might have some mod that interfere with the entity models like animations or cull etc. Might wanna test it out

**Comment by terzag** [comment]
I've just tried to remove basically all my mods and the problem is still there.

I kept only the basics: Sodium, Indum, Iris, Fabric API and ETF (needed by EMF I think). I also kept an extra mod that adds items to the game (labels) and I'm not sure how it would behave if I remove it but the issue with EMF already appeared before I used that mod so I believe I can cross it out.

**Comment by Ryuushen** [comment]
> I've just tried to remove basically all my mods and the problem is still there.
> 
> I kept only the basics: Sodium, Indum, Iris, Fabric API and ETF (needed by EMF I think). I also kept an extra mod that adds items to the game (labels) and I'm not sure how it would behave if I remove it but the issue with EMF already appeared before I used that mod so I believe I can cross it out.

Yeah I feel it. I'm running to another problem right now which is Terr's Veggie Villager. It literally just work fine for 1 and after you restart MC it stopped working even if it's just Rubidium, Rubidium Extras, ETF, EMF. I dont know what the issue is but it's just very unstable with when it works or not rn

**Comment by edricus** [comment]
Villagers also are broken, they're mostly invisible.

**Comment by terzag** [comment]
Yes, can confirm. I hadn't noticed them before.

**Comment by terzag** [comment]
Saw there was an update implementing the missing OptiFine features and so far, all the models that were broken with Mizuno's pack seem to display fine. I've checked pigs, cows, golems and villagers.
