### ISSUE TITLE
[Bug - models] Ravager jaw pivot issue.

### ISSUE THREAD

**Issue by apricotluma** [Traben-0/Entity_Model_Features#88]
Ravager jaw does not pivot correctly.

This seems to occur in any resource pack that uses JEM on ravagers, as I created a new one using the base ravager Blockbench model and the issue occurred even in that state.

In vanilla Minecraft, the ravager's lower jaw should rotate with the head.

![2023-07-29_13 25 15](https://github.com/Traben-0/Entity_Model_Features/assets/119263482/9e4afb48-d42e-41a6-befc-ac3f6693f2bd)
^^ Image of jaw issue using base Blockbench JEM for ravager.
![2023-07-29_13 31 50](https://github.com/Traben-0/Entity_Model_Features/assets/119263482/5bdca223-6c61-4a65-a16b-2f8099b18966)
^^ Normal ravager head rotation. (Jaw has also moved.) 

 - Minecraft Version: 1.19.4, Fabric
 - EMF version: 0.2.13

**Comment by punctdan** [comment]
I can confirm this issue.
