### ISSUE TITLE
[Bug - models]

### ISSUE THREAD

**Issue by DISCH-ORD** [Traben-0/Entity_Model_Features#97]
Does not enable proper use of fresh animations as advertised.

Fresh Animations 1.8.1 with EMF 0.2.13 on Minecraft version 1.20.1 not functioning. Villagers appearing without eyes, and all other mobs appearing as vanilla, with no unique animations or behaviors.

Also using ETF 4.5.1

**Comment by Traben-0** [comment]
Do you have any other mods enabled? Does it work with just etf and emf

**Comment by DISCH-ORD** [comment]
Sorry, I was out and my phone wouldn't let me reply for some reason. I figured out the issue; I didn't notice I had "Better Animations Collection" enabled on curseforge. Sorry about that! The mod works fantastically!!!! Thanks for your contribution.
